import 'package:flutter/material.dart';
List<List<String>> Sounds = List.of([
  List.of([
    "audio/sound1-2.wav",
    "audio/sound1-1.wav",
    "audio/sound1-3.wav",
    "audio/sound1-4.wav",
  ]),
  List.of([
    "audio/sound2-1.wav",
    "audio/sound2-2.wav",
    "audio/sound2-3.wav",
  ]),
  List.of([
    "audio/sound3-1.wav",
    "audio/sound3-2.wav",
    "audio/sound3-3.wav",
  ]),
  List.of([
    "audio/sound4-1.wav",
    "audio/sound4-2.wav",
  ]),
  List.of([
    "audio/sound5-1.wav",
    "audio/sound5-2.wav",
    "audio/sound5-3.wav",
  ]),
  List.of([
    "audio/sound6-1.wav",
    "audio/sound6-2.wav",
  ]),
  List.of([
    "audio/sound7-1.wav",
    "audio/sound7-2.wav",
  ]),
  List.of([
    "audio/sound8-1.wav",
    "audio/sound8-2.wav",
  ]),
  List.of([
    "audio/sound9-1.wav",
    "audio/sound9-2.wav",
  ]),
  List.of([
    "audio/sound10-1.wav",
    "audio/sound10-2.wav",
    "audio/sound10-3.wav",
    "audio/sound10-4.wav",
  ]),
  List.of([
    "audio/sound11-1.wav",
    "audio/sound11-2.wav",
    "audio/sound11-3.wav",
    "audio/sound11-4.wav",
  ]),
  List.of([
    "audio/sound12-1.wav",
    "audio/sound12-2.wav",
    "audio/sound12-3.wav",

  ]),
  List.of([
    "audio/sound13-1.wav",
    "audio/sound13-2.wav",
    "audio/sound13-3.wav",

  ]),
  List.of([
    "audio/sound14-1.wav",
    "audio/sound14-2.wav",
    "audio/sound14-3.wav",

  ]),
  List.of([
    "audio/sound15-1.wav",
    "audio/sound15-2.wav",
    "audio/sound15-3.wav",

  ]),
  List.of([
    "audio/sound16-1.wav",
    "audio/sound16-2.wav",
    "audio/sound16-3.wav",
    "audio/sound16-4.wav",
  ]),
  List.of([
    "audio/sound17-1.wav",
    "audio/sound17-2.wav",
    "audio/sound17-3.wav",

  ]),
  List.of([
    "audio/sound18-1.wav",
    "audio/sound18-2.wav",
    "audio/sound18-3.wav",
    "audio/sound18-4.wav",
  ]),
  List.of([
    "audio/sound19-1.wav",
    "audio/sound19-2.wav",
    "audio/sound19-3.wav",
    "audio/sound19-4.wav",
  ]),
  List.of([
    "audio/sound20-1.wav",
    "audio/sound20-2.wav",
    "audio/sound20-3.wav",

  ]),
  List.of([
    "audio/sound21-1.wav",
    "audio/sound21-2.wav",
    "audio/sound21-3.wav",
    "audio/sound21-4.wav",
  ]),
  List.of([
    "audio/sound22-1.wav",
    "audio/sound22-2.wav",
    "audio/sound22-3.wav",

  ]),
  List.of([
    "audio/sound23-1.wav",
    "audio/sound23-2.wav",
    "audio/sound23-3.wav",
    "audio/sound23-4.wav",
  ]),
  List.of([
    "audio/sound24-1.wav",
    "audio/sound24-2.wav",
    "audio/sound24-3.wav",
    "audio/sound24-4.wav",
    "audio/sound24-5.wav",
  ]),
  List.of([
    "audio/sound25-1.wav",
    "audio/sound25-2.wav",
    "audio/sound25-3.wav",
    "audio/sound25-4.wav",
    "audio/sound25-5.wav",
  ]),
  List.of([
    "audio/sound26-1.wav",
    "audio/sound26-2.wav",
    "audio/sound26-3.wav",
    "audio/sound26-4.wav",
    "audio/sound26-5.wav",
  ]),
  List.of([
    "audio/sound27-1.wav",
    "audio/sound27-2.wav",
    "audio/sound27-3.wav",
    "audio/sound27-4.wav",
  ]),
  List.of([
    "audio/sound28-1.wav",
    "audio/sound28-2.wav",
    "audio/sound28-3.wav",
    "audio/sound28-4.wav",
    "audio/sound28-5.wav",
  ]),
  List.of([
    "audio/sound29-1.wav",
    "audio/sound29-2.wav",
    "audio/sound29-3.wav",
    "audio/sound29-4.wav",
    "audio/sound29-5.wav",
  ]),
  List.of([
    "audio/sound30-1.wav",
    "audio/sound30-2.wav",
    "audio/sound30-3.wav",
  ]),
  List.of([
    "audio/sound31-1.wav",
    "audio/sound31-2.wav",
    "audio/sound31-3.wav",
    "audio/sound31-4.wav",
    "audio/sound31-5.wav",
  ]),
  List.of([
    "audio/sound32-1.wav",
    "audio/sound32-2.wav",
    "audio/sound32-3.wav",
    "audio/sound32-4.wav",
    "audio/sound32-5.wav",
  ]),
  List.of([
    "audio/sound33-1.wav",
    "audio/sound33-2.wav",
    "audio/sound33-3.wav",
    "audio/sound33-4.wav",
    "audio/sound33-5.wav",
  ]),
  List.of([
    "audio/sound34-1.wav",
    "audio/sound34-2.wav",
    "audio/sound34-3.wav",
    "audio/sound34-4.wav",
    "audio/sound34-5.wav",
  ]),
  List.of([
    "audio/sound35-1.wav",
    "audio/sound35-2.wav",
    "audio/sound35-3.wav",
    "audio/sound35-4.wav",
    "audio/sound35-5.wav",
  ]),
  List.of([
    "audio/sound36-1.wav",
    "audio/sound36-2.wav",
    "audio/sound36-3.wav",
    "audio/sound36-4.wav",
  ]),
  List.of([
    "audio/sound37-1.wav",
    "audio/sound37-2.wav",
    "audio/sound37-3.wav",
    "audio/sound37-4.wav",
    "audio/sound37-5.wav",
    "audio/sound37-6.wav",
  ]),
  List.of([
    "audio/sound38-1.wav",
    "audio/sound38-2.wav",
    "audio/sound38-3.wav",
    "audio/sound38-4.wav",
    "audio/sound38-5.wav",
  ]),
  List.of([
    "audio/sound39-1.wav",
    "audio/sound39-2.wav",
    "audio/sound39-3.wav",
    "audio/sound39-4.wav",
    "audio/sound39-5.wav",
    "audio/sound39-6.wav",
    "audio/sound39-7.wav",
  ]),
  List.of([
    "audio/sound40-1.wav",
    "audio/sound40-2.wav",
    "audio/sound40-3.wav",
    "audio/sound40-4.wav",
    "audio/sound40-5.wav",
    "audio/sound40-6.wav",
    "audio/sound40-7.wav",
  ]),
  List.of([
    "audio/sound41-1.wav",
    "audio/sound41-2.wav",
    "audio/sound41-3.wav",
    "audio/sound41-4.wav",
    "audio/sound41-5.wav",
    "audio/sound41-6.wav",
    "audio/sound41-7.wav",
    "audio/sound41-8.wav",
  ]),
  List.of([
    "audio/sound42-1.wav",
    "audio/sound42-2.wav",
    "audio/sound42-3.wav",
    "audio/sound42-4.wav",
    "audio/sound42-5.wav",
    "audio/sound42-6.wav",
  ]),
  List.of([
    "audio/sound43-1.wav",
    "audio/sound43-2.wav",
    "audio/sound43-3.wav",
    "audio/sound43-4.wav",
    "audio/sound43-5.wav",
    "audio/sound43-6.wav",
  ]),
  List.of([
    "audio/sound44-1.wav",
    "audio/sound44-2.wav",
    "audio/sound44-3.wav",
    "audio/sound44-4.wav",
    "audio/sound44-5.wav",
    "audio/sound44-6.wav",
  ]),
  List.of([
    "audio/sound45-1.wav",
    "audio/sound45-2.wav",
    "audio/sound45-3.wav",
    "audio/sound45-4.wav",
    "audio/sound45-5.wav",
    "audio/sound45-6.wav",
    "audio/sound45-7.wav",
  ]),
  List.of([
    "audio/sound46-1.wav",
    "audio/sound46-2.wav",
    "audio/sound46-3.wav",
    "audio/sound46-4.wav",
    "audio/sound46-5.wav",
  ]),
  List.of([
    "audio/sound47-1.wav",
    "audio/sound47-2.wav",
    "audio/sound47-3.wav",
    "audio/sound47-4.wav",
  ]),
  List.of([
    "audio/sound48-1.wav",
    "audio/sound48-2.wav",
    "audio/sound48-3.wav",
    "audio/sound48-4.wav",
    "audio/sound48-5.wav",
    "audio/sound48-6.wav",
  ]),
  List.of([
    "audio/sound49-1.wav",
    "audio/sound49-2.wav",
    "audio/sound49-3.wav",
    "audio/sound49-4.wav",
    "audio/sound49-5.wav",
    "audio/sound49-6.wav",
    "audio/sound49-7.wav",
    "audio/sound49-8.wav",
    "audio/sound49-9.wav",
  ]),
  List.of([
    "audio/sound50-1.wav",
    "audio/sound50-2.wav",
    "audio/sound50-3.wav",
    "audio/sound50-4.wav",
    "audio/sound50-5.wav",
    "audio/sound50-6.wav",
    "audio/sound50-7.wav",
  ]),
  List.of([
    "audio/sound51-1.wav",
    "audio/sound51-2.wav",
    "audio/sound51-3.wav",
    "audio/sound51-4.wav",
    "audio/sound51-5.wav",
    "audio/sound51-6.wav",
    "audio/sound51-7.wav",
    "audio/sound51-8.wav",
  ]),
  List.of([
    "audio/sound52-1.wav",
    "audio/sound52-2.wav",
    "audio/sound52-3.wav",
    "audio/sound52-4.wav",
    "audio/sound52-5.wav",
    "audio/sound52-6.wav",
  ]),
  List.of([
    "audio/sound53-1.wav",
    "audio/sound53-2.wav",
    "audio/sound53-3.wav",
    "audio/sound53-4.wav",
    "audio/sound53-5.wav",
  ]),
]);
List<List<List<Cell>>> allLevels = List.of([

    List.of([
      List.of([Cell(3, "У"), Cell(3, "Ж"), Cell(1, "П"),]),
      List.of([Cell(4, "У"), Cell(4, "Н"), Cell(1, "У"), ]),
      List.of([Cell(4, "Д"), Cell(2, "Ы"), Cell(2, "Ж"), ]),
    ]),List.of([
      List.of([Cell(1, "Ж"), Cell(3, "Р"), Cell(2, "Ы"),]),
      List.of([Cell(1, "Ы"), Cell(3, "А"), Cell(2, "П"), ]),
      List.of([Cell(1, "П"), Cell(2, "Т"), Cell(2, "Ы"), ]),
    ]),List.of([
      List.of([Cell(2, "Д"), Cell(1, "Ы"), Cell(1, "Ж"),]),
      List.of([Cell(2, "У"), Cell(1, "В"), Cell(3, "К"), ]),
      List.of([Cell(2, "Р"), Cell(3, "Й"), Cell(3, "Ы"), ]),
    ]),List.of([
      List.of([Cell(1, "Б"), Cell(2, "Ы"), Cell(2, "Р"),]),
      List.of([Cell(1, "А"), Cell(2, "Н"), Cell(2, "У"), ]),
      List.of([Cell(1, "К"), Cell(1, "А"), Cell(2, "Т"), ]),
    ]),List.of([
      List.of([Cell(1, "С"), Cell(3, "У"), Cell(3, "Г"),]),
      List.of([Cell(1, "А"), Cell(3, "М"), Cell(2, "Ш"), ]),
      List.of([Cell(1, "Е"), Cell(1, "С"), Cell(2, "Э"), ]),
    ]),List.of([
      List.of([Cell(1, "И"), Cell(1, "В"), Cell(1, "О"),]),
      List.of([Cell(2, "Ӧ"), Cell(2, "Д"), Cell(1, "Р"), ]),
      List.of([Cell(2, "Д"), Cell(2, "Ь"), Cell(2, "Ы"), ]),
    ]),List.of([
      List.of([Cell(1, "Ӧ"), Cell(1, "Й"), Cell(2, "Т"),]),
      List.of([Cell(1, "П"), Cell(1, "Ш"), Cell(2, "Ӥ"), ]),
      List.of([Cell(1, "Р"), Cell(1, "У"), Cell(2, "Р"), ]),
    ]),List.of([
      List.of([Cell(1, "А"), Cell(1, "П"), Cell(1, "А"),]),
      List.of([Cell(2, "Е"), Cell(2, "К"), Cell(1, "Й"), ]),
      List.of([Cell(2, "Н"), Cell(2, "Е"), Cell(2, "Ш"), ]),
    ]),List.of([
      List.of([Cell(1, "М"), Cell(1, "А"), Cell(1, "Л"),]),
      List.of([Cell(2, "У"), Cell(2, "Б"), Cell(1, "П"), ]),
      List.of([Cell(2, "С"), Cell(1, "Н"), Cell(1, "А"), ]),
    ]),


    List.of([
      List.of([Cell(1, "Н"), Cell(1, "О"), Cell(2, "Ӟ"),Cell(2, "Ы"),]),
      List.of([Cell(1, "К"), Cell(1, "И"), Cell(2, "И"), Cell(2, "Ч"),]),
      List.of([Cell(3, "О"), Cell(3, "Ш"), Cell(4, "Р"), Cell(4, "Ы")]),
      List.of([Cell(4, "Г"), Cell(4, "О"), Cell(4, "Н"), Cell(4, "Д"),])
    ]), List.of([
      List.of([Cell(1, "К"), Cell(1, "О"), Cell(3, "А"), Cell(3, "Р"),]),
      List.of([Cell(1, "К"), Cell(1, "Р"),Cell(3, "У"), Cell(3, "К"),]),
      List.of([Cell(1, "А"), Cell(2, "Н"),Cell(2, "О") ,Cell(4, "К") ]),
      List.of([Cell(2, "У"),Cell(2, "К") ,Cell(4, "Ӝ") , Cell(4, "Ӧ"),])
    ]), List.of([
      List.of([Cell(1, "К"), Cell(3, "Б"), Cell(3, "Е"), Cell(3, "Р"),]),
      List.of([Cell(1, "У"), Cell(2, "У"), Cell(2, "Н"), Cell(3, "И"),]),
      List.of([Cell(1, "А"), Cell(2, "Ш") , Cell(2, "Д"), Cell(3, "З")]),
      List.of([Cell(1, "К"), Cell(1, "А"), Cell(2, "Ы"), Cell(3, "Ь"),])
    ]), List.of([
      List.of([Cell(2, "Ч"), Cell(2, "О"), Cell(2, "Р"), Cell(2, "Ы"),]),
      List.of([Cell(1, "С"), Cell(1, "Ь"), Cell(3, "К"), Cell(2, "Г"),]),
      List.of([Cell(1, "Ю"), Cell(1, "С") , Cell(3, "Е"), Cell(3, "Ш")]),
      List.of([Cell(1, "К"), Cell(1, "А"), Cell(3, "Р"), Cell(3, "Ы"),])
    ]),List.of([
      List.of([Cell(1, "С"), Cell(1, "У"), Cell(1, "Г"), Cell(3, "Н"),]),
      List.of([Cell(2, "К"), Cell(2, "Е"), Cell(1, "О"), Cell(3, "Ё"),]),
      List.of([Cell(2, "А"), Cell(2, "С") , Cell(1, "Н"), Cell(3, "С")]),
      List.of([Cell(2, "М"), Cell(3, "П"), Cell(3, "У"), Cell(3, "К"),])
    ]),List.of([
      List.of([Cell(2, "М"), Cell(2, "А"), Cell(2, "Б"), Cell(3, "П"),]),
      List.of([Cell(1, "А"), Cell(1, "Р"), Cell(1, "Ъ"), Cell(3, "Ы"),]),
      List.of([Cell(3, "Н"), Cell(1, "Н") , Cell(1, "Я"), Cell(3, "Ш")]),
      List.of([Cell(3, "Ы"), Cell(3, "Р"), Cell(3, "У"), Cell(3, "Т"),])
    ]),List.of([
      List.of([Cell(3, "Й"), Cell(4, "К"), Cell(4, "Ы"), Cell(2, "Н"),]),
      List.of([Cell(3, "Ы"), Cell(4, "А"), Cell(2, "Р"), Cell(2, "Ы"),]),
      List.of([Cell(3, "Р"), Cell(4, "Р") , Cell(4, "А"), Cell(1, "Ь")]),
      List.of([Cell(1, "Э"), Cell(1, "М"), Cell(1, "Е"), Cell(1, "З"),])
    ]),List.of([
      List.of([Cell(1, "К"), Cell(1, "Ы"), Cell(1, "Л"), Cell(1, "Р"),]),
      List.of([Cell(2, "М"), Cell(3, "Л"), Cell(1, "Б"), Cell(1, "У"),]),
      List.of([Cell(2, "А"), Cell(3, "А") , Cell(3, "К"), Cell(3, "С")]),
      List.of([Cell(2, "Й"), Cell(2, "Т"), Cell(2, "А"), Cell(2, "Л"),])
    ]),List.of([
      List.of([Cell(4, "Л"), Cell(4, "Ь"), Cell(4, "Ӧ"), Cell(4, "М"),]),
      List.of([Cell(3, "К"), Cell(3, "Е"), Cell(3, "Т"), Cell(1, "К"),]),
      List.of([Cell(3, "Ы"), Cell(3, "Ш") , Cell(1, "Т"), Cell(1, "У")]),
      List.of([Cell(2, "Ы"), Cell(2, "Ь"), Cell(2, "З"), Cell(2, "И"),])
    ]),List.of([
      List.of([Cell(4, "Н"), Cell(4, "Ю"), Cell(4, "Л"), Cell(1, "К"),]),
      List.of([Cell(3, "Ӵ"), Cell(3, "Ӧ"), Cell(4, "Э"), Cell(1, "Ы"),]),
      List.of([Cell(2, "М"), Cell(3, "Ж") , Cell(4, "С"), Cell(1, "З")]),
      List.of([Cell(2, "Е"), Cell(2, "Ж"), Cell(2, "У"), Cell(2, "Г"),])
    ]),List.of([
      List.of([Cell(1, "Ч"), Cell(1, "И"), Cell(1, "Б"), Cell(3, "Ы"),]),
      List.of([Cell(1, "Ь"), Cell(1, "Н"), Cell(1,"И"), Cell(3, "Т"),]),
      List.of([Cell(3, "Т"), Cell(3, "У") , Cell(3, "С"), Cell(3, "Ь")]),
      List.of([Cell(2, "Ь"), Cell(2, "Л"), Cell(2, "Ӥ"), Cell(2, "С"),])
    ]),List.of([
      List.of([Cell(3, "Ж"), Cell(3, "Ы"), Cell(4, "А"), Cell(4, "Н"),]),
      List.of([Cell(2, "Т"), Cell(3, "Б"), Cell(4,"Й"), Cell(4, "А"),]),
      List.of([Cell(2, "Р"), Cell(1, "М") , Cell(1, "У"), Cell(1, "Н")]),
      List.of([Cell(2, "О"), Cell(2, "К"), Cell(1, "О"), Cell(1, "Ч"),])
    ]),List.of([
      List.of([Cell(3, "А"), Cell(3, "З"), Cell(3, "Е"), Cell(3, "Г"),]),
      List.of([Cell(3, "Ӟ"), Cell(1, "Л"), Cell(1,"Я"), Cell(1, "Л"),]),
      List.of([Cell(2, "Н"), Cell(2, "У") , Cell(2, "В"), Cell(1, "Ь")]),
      List.of([Cell(2, "Ы"), Cell(2, "Л"), Cell(1, "И"), Cell(1, "Ч"),])
    ]),List.of([
      List.of([Cell(3, "С"), Cell(3, "Ӥ"), Cell(3, "Д"), Cell(2, "К"),]),
      List.of([Cell(3, "Ь"), Cell(1, "Ы"), Cell(1,"Н"), Cell(2, "А"),]),
      List.of([Cell(4, "Д"), Cell(1, "В") , Cell(2, "Н"), Cell(2, "Р")]),
      List.of([Cell(4, "И"), Cell(4, "Г"), Cell(2, "А"), Cell(2, "Н"),])
    ]),



    List.of([
      List.of([Cell(2, "Л"), Cell(2, "Э"), Cell(2, "З"),Cell(4, "Д"),Cell(4, "А")]),
      List.of([Cell(2, "О"), Cell(3, "Р"), Cell(2, "Ь"), Cell(4, "Н"),Cell(4, "Н")]),
      List.of([Cell(2, "Т"), Cell(3, "А"), Cell(3, "Б"), Cell(4, "А"),Cell(5, "В")]),
      List.of([Cell(1, "И"), Cell(1, "С"), Cell(3, "З"), Cell(3, "А"),Cell(5, "И")]),
      List.of([Cell(1, "П"), Cell(1, "П"), Cell(1, "У"), Cell(5, "Ь"),Cell(5, "З")]),
    ]),List.of([
      List.of([Cell(1, "В"), Cell(5, "С"), Cell(5, "О"),Cell(5, "Р"),Cell(2, "Б")]),
      List.of([Cell(1, "О"), Cell(1, "З"), Cell(1, "Ь"), Cell(5, "Ё"),Cell(2, "А")]),
      List.of([Cell(3, "Ӥ"), Cell(3, "Н"), Cell(2, "Р"), Cell(2, "Ы"),Cell(2, "Т")]),
      List.of([Cell(3, "Д"), Cell(4, "И"), Cell(4, "Б"), Cell(4, "Ё"),Cell(4, "Ӧ")]),
      List.of([Cell(3, "Е"), Cell(3, "В"), Cell(4, "У"), Cell(4, "Г"),Cell(4, "В")]),
    ]),List.of([
      List.of([Cell(3, "Б"), Cell(3, "Ч"), Cell(3, "А"),Cell(4, "Г"), Cell(4, "У")]),
      List.of([Cell(3, "А"), Cell(3, "К"), Cell(2, "В"), Cell(5, "О"),Cell(4, "Д")]),
      List.of([Cell(2, "Э"), Cell(2, "Т"), Cell(2, "О"), Cell(5, "Б"),Cell(4, "Ы")]),
      List.of([Cell(2, "С"), Cell(5, "У"), Cell(5, "Р"), Cell(5, "О"),Cell(4, "Р")]),
      List.of([Cell(1, "Ш"), Cell(1, "Ы"), Cell(1, "М"), Cell(1, "Е"),Cell(4, "И")]),
    ]),List.of([
      List.of([Cell(1, "Д"), Cell(1, "Ы"), Cell(1, "Ш"),Cell(1, "Е"), Cell(1, "Т")]),
      List.of([Cell(3, "Д"), Cell(3, "Л"), Cell(3, "Ӧ"), Cell(1, "К"),Cell(1, "С")]),
      List.of([Cell(3, "Э"), Cell(2, "Ь"), Cell(3, "В"), Cell(1, "О"),Cell(4, "А")]),
      List.of([Cell(3, "Т"), Cell(2, "Н"), Cell(4, "И"), Cell(1, "Н"),Cell(4, "Р")]),
      List.of([Cell(2, "В"), Cell(2, "Е"), Cell(4, "Р"), Cell(4, "Е"),Cell(4, "Б")]),
    ]),List.of([
      List.of([Cell(2, "Ӝ"), Cell(2, "Ӧ"), Cell(1, "У"),Cell(1, "Й"), Cell(1, "В")]),
      List.of([Cell(2, "К"), Cell(2, "К"), Cell(4, "Л"), Cell(5, "К"),Cell(1, "Ӧ")]),
      List.of([Cell(2, "Ы"), Cell(4, "П"), Cell(4, "А"), Cell(5, "О"),Cell(1, "Т")]),
      List.of([Cell(2, "Ш"), Cell(4, "А"), Cell(4, "С"), Cell(5, "Ӵ"),Cell(5, "Ы")]),
      List.of([Cell(2, "Е"), Cell(2, "Т"), Cell(3, "С"), Cell(3, "Ӧ"),Cell(5, "Ш")]),
    ]),List.of([
      List.of([Cell(1, "А"), Cell(1, "Д"), Cell(1, "Я"),Cell(4, "В"), Cell(4, "А")]),
      List.of([Cell(3, "У"), Cell(3, "Д"), Cell(1, "М"), Cell(1, "И"),Cell(4, "М")]),
      List.of([Cell(3, "Ш"), Cell(3, "Е"), Cell(3, "С"), Cell(5, "С"),Cell(4, "Ы")]),
      List.of([Cell(5, "Г"), Cell(5, "Е"), Cell(5, "Р"), Cell(5, "Э"),Cell(4, "Ш")]),
      List.of([Cell(2, "Э"), Cell(2, "К"), Cell(2, "С"), Cell(2, "Э"),Cell(2, "Й")]),
    ]),List.of([
      List.of([Cell(1, "В"), Cell(1, "И"), Cell(1, "Р"),Cell(1, "Н"), Cell(3, "Т")]),
      List.of([Cell(2, "Г"), Cell(1, "А"), Cell(1, "Н"), Cell(1, "У"),Cell(3, "А")]),
      List.of([Cell(2, "О"), Cell(1, "Л"), Cell(2, "М"), Cell(2, "А"),Cell(3, "Ш")]),
      List.of([Cell(2, "Р"), Cell(2, "У"), Cell(2, "Ш"), Cell(2, "Н"),Cell(3, "Б")]),
      List.of([Cell(2, "Д"), Cell(2, "К"), Cell(3, "А"), Cell(3, "К"),Cell(3, "А")]),
    ]),List.of([
      List.of([Cell(4, "Л"), Cell(4, "Ы"), Cell(4, "М"),Cell(3, "Ю"), Cell(3, "С")]),
      List.of([Cell(2, "К"), Cell(3, "Л"), Cell(4, "Ы"), Cell(3, "С"),Cell(1, "Й")]),
      List.of([Cell(2, "У"), Cell(3, "Ы"), Cell(3, "Т"), Cell(3, "Ь"),Cell(1, "Ӧ")]),
      List.of([Cell(2, "Р"), Cell(2, "Е"), Cell(2, "Г"), Cell(5, "К"),Cell(5, "Ы")]),
      List.of([Cell(5, "В"), Cell(5, "Ы"), Cell(5, "Ж"), Cell(5, "Ы"),Cell(5, "Л")]),
    ]),List.of([
      List.of([Cell(2, "Т"), Cell(1, "А"), Cell(1, "Т"),Cell(1, "А"), Cell(5, "Ы")]),
      List.of([Cell(2, "Э"), Cell(4, "Б"), Cell(4, "Ӧ"), Cell(1, "С"),Cell(5, "Р")]),
      List.of([Cell(2, "Л"), Cell(2, "Ь"), Cell(4, "Д"), Cell(5, "Д"),Cell(5, "У")]),
      List.of([Cell(3, "О"), Cell(3, "Р"), Cell(4, "Ё"), Cell(4, "Н"),Cell(4, "О")]),
      List.of([Cell(3, "З"), Cell(3, "К"), Cell(3, "И"), Cell(3, "Б"),Cell(3, "Ы")]),
    ]),List.of([
      List.of([Cell(2, "Б"), Cell(3, "Т"), Cell(3, "Ы"),Cell(3, "М"), Cell(3, "Е")]),
      List.of([Cell(2, "У"), Cell(1, "Ы"), Cell(1, "З"), Cell(1, "У"),Cell(3, "Т")]),
      List.of([Cell(2, "Б"), Cell(2, "Ы"), Cell(2, "Л"), Cell(2, "И"),Cell(4, "Л")]),
      List.of([Cell(4, "Й"), Cell(4, "Э"), Cell(4, "Т"), Cell(4, "М"),Cell(4, "Е")]),
      List.of([Cell(5, "А"), Cell(5, "Й"), Cell(5, "Ш"), Cell(5, "Е"),Cell(5, "Т")]),
    ]),List.of([
      List.of([Cell(1, "Ӟ"), Cell(1, "О"), Cell(1, "Л"), Cell(1, "Ь"),Cell(2, "Н")]),
      List.of([Cell(5, "Л"), Cell(1, "Р"), Cell(1, "Ы"), Cell(1, "Г"),Cell(2, "У")]),
      List.of([Cell(5, "Ы"), Cell(1, "И"), Cell(3, "Ь"), Cell(4, "Ӵ"),Cell(2, "М")]),
      List.of([Cell(5, "Ь"), Cell(3, "Ю"), Cell(3, "С"), Cell(4, "Ы"),Cell(2, "Ы")]),
      List.of([Cell(5, "З"), Cell(5, "Ӥ"), Cell(5, "С"), Cell(4, "Н"),Cell(2, "Р")]),
    ]),List.of([
      List.of([Cell(1, "К"), Cell(1, "У"), Cell(1, "Ж"), Cell(4, "К"),Cell(4, "У")]),
      List.of([Cell(2, "Н"), Cell(2, "Я"), Cell(1, "Ы"), Cell(4, "З"),Cell(4, "А")]),
      List.of([Cell(2, "Ь"), Cell(2, "Н"), Cell(1, "М"), Cell(4, "Ь"),Cell(5, "Р")]),
      List.of([Cell(3, "Т"), Cell(3, "Ы"), Cell(3, "Р"), Cell(5, "Г"),Cell(5, "У")]),
      List.of([Cell(3, "Ы"), Cell(3, "П"), Cell(3, "Т"), Cell(3, "О"),Cell(3, "Н")]),
    ]),List.of([
      List.of([Cell(1, "Э"), Cell(1, "Б"), Cell(4, "П"), Cell(4, "А"),Cell(4, "Н")]),
      List.of([Cell(3, "Ы"), Cell(1, "Е"), Cell(4, "Э"), Cell(4, "Т"),Cell(4, "Ь")]),
      List.of([Cell(3, "Ч"), Cell(1, "К"), Cell(4, "М"), Cell(2, "М"),Cell(2, "У")]),
      List.of([Cell(3, "Т"), Cell(2, "П"), Cell(2, "У"), Cell(2, "Ш"),Cell(2, "Л")]),
      List.of([Cell(3, "Р"), Cell(3, "Я"), Cell(3, "С"), Cell(2, "Ы"),Cell(2, "Ь")]),
    ]),List.of([
      List.of([Cell(1, "Ш"), Cell(1, "Ы"), Cell(1, "Д"), Cell(6, "В"),Cell(6, "У")]),
      List.of([Cell(3, "П"), Cell(2, "Ы"), Cell(2, "М"), Cell(2, "Е"),Cell(2, "С")]),
      List.of([Cell(3, "Е"), Cell(2, "К"), Cell(3, "Я"), Cell(3, "Н"),Cell(4, "В")]),
      List.of([Cell(3, "Л"), Cell(3, "Ь"), Cell(3, "Н"), Cell(3, "Ь"),Cell(4, "А")]),
      List.of([Cell(5, "И"), Cell(5, "Б"), Cell(5, "У"), Cell(5, "Г"),Cell(4, "Л")]),
    ]),List.of([
      List.of([Cell(1, "Ч"), Cell(1, "И"), Cell(1, "Н"),Cell(3, "Б"),Cell(3, "Ы")]),
      List.of([Cell(2, "П"), Cell(1, "Ы"), Cell(1, "Ь"), Cell(3, "О"),Cell(3, "Р")]),
      List.of([Cell(2, "А"), Cell(2, "Л"), Cell(2, "Э"), Cell(2, "З"),Cell(2, "Ь")]),
      List.of([Cell(5, "Б"), Cell(5, "Я"), Cell(5, "Р"), Cell(4, "Л"),Cell(4, "Ы")]),
      List.of([Cell(5, "А"), Cell(5, "Д"), Cell(4, "Т"), Cell(4, "У"),Cell(4, "С")]),
    ]),




   List.of([
      List.of([Cell(4, "П"), Cell(4, "Ы"), Cell(4, "Ӵ"), Cell(4, "А"),Cell(4, "Л"),Cell(6, "Л"),]),
      List.of([Cell(5, "Б"), Cell(5, "У"), Cell(5, "Д"), Cell(5, "О"),Cell(6, "М"),Cell(6, "Ы"),]),
      List.of([Cell(2, "Л"), Cell(2, "Э"), Cell(2, "К"), Cell(5, "С"),Cell(6, "Ы"),Cell(7, "Г"),]),
      List.of([Cell(2, "А"), Cell(1, "Ч"), Cell(2, "Т"), Cell(2, "О"),Cell(7, "Р"),Cell(7, "У"),]),
      List.of([Cell(2, "В"), Cell(1, "Е"), Cell(1, "Б"), Cell(2, "Н"),Cell(3, "Й"),Cell(3, "Ы"),]),
      List.of([Cell(1, "Г"), Cell(1, "У"), Cell(1, "Л"), Cell(3, "И"),Cell(3, "С"),Cell(3, "Р"),]),
    ]),List.of([
      List.of([Cell(4, "П"), Cell(3, "З"), Cell(3, "Ъ"), Cell(3, "Е"),Cell(3, "М"),Cell(7, "Н"),]),
      List.of([Cell(4, "А"), Cell(3, "У"), Cell(1, "А"), Cell(1, "Г"),Cell(7, "М"),Cell(7, "О"),]),
      List.of([Cell(4, "С"), Cell(3, "М"), Cell(1, "Й"), Cell(1, "А"),Cell(7, "Ш"),Cell(7, "У"),]),
      List.of([Cell(4, "Ь"), Cell(2, "Н"), Cell(2, "Ю"), Cell(2, "К"),Cell(6, "Н"),Cell(7, "Т"),]),
      List.of([Cell(5, "Е"), Cell(5, "Т"), Cell(5, "Ӥ"), Cell(5, "Н"),Cell(6, "А"),Cell(6, "Н"),]),
      List.of([Cell(6, "В"), Cell(6, "И"), Cell(6, "З"), Cell(6, "Ь"),Cell(6, "С"),Cell(6, "Ы"),]),
    ]),List.of([
    List.of([Cell(8, "М"), Cell(8, "Л"), Cell(8, "И"), Cell(8, "М"),Cell(5, "Н"),Cell(6, "Ы"),]),
    List.of([Cell(8, "Ы"), Cell(8, "Ь"), Cell(5, "О"), Cell(5, "Г"),Cell(5, "И"),Cell(6, "Н"),]),
    List.of([Cell(4, "С"), Cell(4, "У"), Cell(4, "Д"), Cell(7, "Ж"),Cell(7, "И"),Cell(6, "У"),]),
    List.of([Cell(3, "Г"), Cell(4, "Р"), Cell(4, "Е"), Cell(7, "Ы"),Cell(7, "Г"),Cell(6, "П"),]),
    List.of([Cell(3, "О"), Cell(3, "З"), Cell(3, "Ы"), Cell(1, "И"),Cell(1, "Н"),Cell(1, "Б"),]),
    List.of([Cell(2, "Р"), Cell(2, "У"), Cell(2, "А"), Cell(2, "Д"),Cell(1, "М"),Cell(1, "А"),]),
  ]),List.of([
      List.of([Cell(5, "А"), Cell(1, "В"), Cell(1, "Е"), Cell(1, "К"),Cell(1, "О"),Cell(1, "Н"),]),
      List.of([Cell(5, "Р"), Cell(5, "А"), Cell(1, "Р"), Cell(1, "Ь"),Cell(6, "О"),Cell(6, "Г"),]),
      List.of([Cell(5, "А"), Cell(5, "М"), Cell(1, "А"), Cell(1, "С"),Cell(6, "Н"),Cell(6, "Р"),]),
      List.of([Cell(2, "К"), Cell(4, "Р"), Cell(4, "Ӧ"), Cell(4, "Ь"),Cell(4, "С"),Cell(6, "Ы"),]),
      List.of([Cell(2, "У"), Cell(2, "А"), Cell(2, "Н"), Cell(4, "И"),Cell(4, "Н"),Cell(3, "Ы"),]),
      List.of([Cell(2, "Ш"), Cell(2, "М"), Cell(3, "Г"), Cell(3, "Ы"),Cell(3, "Р"),Cell(3, "Л"),]),
    ]),List.of([
      List.of([Cell(1, "Я"), Cell(1, "Р"), Cell(5, "Т"), Cell(5, "Е"),Cell(5, "Р"),Cell(5, "Е"),]),
      List.of([Cell(2, "К"), Cell(1, "А"), Cell(1, "Т"), Cell(1, "О"),Cell(1, "Н"),Cell(5, "Б"),]),
      List.of([Cell(2, "А"), Cell(2, "А"), Cell(5, "У"), Cell(5, "Л"),Cell(5, "Ч"),Cell(5, "Е"),]),
      List.of([Cell(2, "П"), Cell(2, "К"), Cell(5, "Л"), Cell(4, "Г"),Cell(4, "У"),Cell(4, "Р"),]),
      List.of([Cell(6, "Р"), Cell(6, "Э"), Cell(6, "Д"), Cell(3, "Е"),Cell(3, "Л"),Cell(4, "Т"),]),
      List.of([Cell(6, "М"), Cell(6, "И"), Cell(6, "Н"), Cell(3, "С"),Cell(3, "А"),Cell(3, "В"),]),
    ]),List.of([
      List.of([Cell(1, "В"), Cell(1, "А"), Cell(1, "Р"), Cell(3, "Г"),Cell(3, "А"),Cell(3, "Ж"),]),
      List.of([Cell(1, "У"), Cell(1, "К"), Cell(1, "Н"), Cell(4, "Г"),Cell(3, "Н"),Cell(3, "А"),]),
      List.of([Cell(2, "Г"), Cell(5, "Г"), Cell(1, "А"), Cell(4, "О"),Cell(4, "Р"),Cell(4, "Д"),]),
      List.of([Cell(2, "Е"), Cell(5, "У"), Cell(1, "Н"), Cell(5, "Р"),Cell(6, "Л"),Cell(4, "С"),]),
      List.of([Cell(2, "Р"), Cell(5, "Ж"), Cell(5, "Д"), Cell(5, "О"),Cell(6, "Я"),Cell(4, "Ю"),]),
      List.of([Cell(2, "Ы"), Cell(6, "Ӵ"), Cell(6, "У"), Cell(6, "Ш"),Cell(6, "Ъ"),Cell(4, "Й"),]),
    ]),List.of([
      List.of([Cell(1, "С"), Cell(3, "К"), Cell(3, "Ы"), Cell(3, "Й"),Cell(3, "О"),Cell(3, "К"),]),
      List.of([Cell(1, "Ю"), Cell(4, "И"), Cell(4, "И"), Cell(4, "Р"),Cell(6, "Н"),Cell(6, "О"),]),
      List.of([Cell(1, "Л"), Cell(4, "Ч"), Cell(4, "Н"), Cell(4, "У"),Cell(4, "Д"),Cell(6, "К"),]),
      List.of([Cell(1, "Э"), Cell(1, "М"), Cell(7, "У"), Cell(7, "Л"),Cell(6, "П"),Cell(6, "У"),]),
      List.of([Cell(2, "У"), Cell(2, "Ж"), Cell(7, "О"), Cell(7, "М"),Cell(5, "М"),Cell(5, "Е"),]),
      List.of([Cell(2, "П"), Cell(2, "Ы"), Cell(2, "М"), Cell(5, "Д"),Cell(5, "Э"),Cell(5, "Р"),]),
    ]),List.of([
      List.of([Cell(1, "В"), Cell(1, "О"), Cell(1, "Ж"), Cell(1, "В"),Cell(3, "Д"),Cell(3, "А"),]),
      List.of([Cell(2, "О"), Cell(1, "С"), Cell(1, "Я"), Cell(1, "Ы"),Cell(5, "Э"),Cell(3, "Р"),]),
      List.of([Cell(2, "Ж"), Cell(1, "Ь"), Cell(1, "Ъ"), Cell(1, "Л"),Cell(5, "Ш"),Cell(3, "Т"),]),
      List.of([Cell(2, "Г"), Cell(1, "К"), Cell(1, "О"), Cell(1, "Н"),Cell(5, "Ъ"),Cell(5, "Я"),]),
      List.of([Cell(2, "А"), Cell(2, "И"), Cell(4, "С"), Cell(5, "Н"),Cell(5, "О"),Cell(5, "С"),]),
      List.of([Cell(2, "Р"), Cell(2, "Ч"), Cell(4, "И"), Cell(4, "Н"),Cell(5, "К"),Cell(5, "Ь"),]),
    ]),List.of([
      List.of([Cell(2, "Ӵ"), Cell(3, "Ы"), Cell(3, "Г"), Cell(3, "У"),Cell(3, "Б"),Cell(3, "И"),]),
      List.of([Cell(2, "О"), Cell(3, "Ь"), Cell(3, "Д"), Cell(4, "Я"),Cell(4, "С"),Cell(4, "Ь"),]),
      List.of([Cell(2, "Ш"), Cell(2, "А"), Cell(3, "Ӧ"), Cell(4, "Ъ"),Cell(4, "О"),Cell(4, "К"),]),
      List.of([Cell(2, "С"), Cell(2, "Т"), Cell(3, "Т"), Cell(4, "Р"),Cell(4, "Н"),Cell(1, "Ы"),]),
      List.of([Cell(2, "К"), Cell(2, "О"), Cell(2, "Н"), Cell(4, "Ы"),Cell(1, "Н"),Cell(1, "Ь"),]),
      List.of([Cell(4, "Ш"), Cell(4, "У"), Cell(4, "Л"), Cell(4, "Д"),Cell(1, "У"),Cell(1, "П"),]),
    ]),List.of([
      List.of([Cell(2, "Л"), Cell(2, "Ӥ"), Cell(2, "Я"), Cell(2, "Л"),Cell(2, "Б"),Cell(2, "И"),]),
      List.of([Cell(1, "Л"), Cell(1, "Ы"), Cell(1, "М"), Cell(2, "Г"),Cell(2, "У"),Cell(4, "Л"),]),
      List.of([Cell(6, "Г"), Cell(1, "П"), Cell(1, "Ы"), Cell(3, "Е"),Cell(3, "Ч"),Cell(4, "У"),]),
      List.of([Cell(6, "У"), Cell(1, "О"), Cell(1, "Г"), Cell(3, "Р"),Cell(3, "Г"),Cell(4, "Д"),]),
      List.of([Cell(6, "Р"), Cell(6, "Е"), Cell(5, "Е"), Cell(5, "С"),Cell(3, "О"),Cell(5, "Й"),]),
      List.of([Cell(6, "Ь"), Cell(6, "З"), Cell(5, "П"), Cell(5, "Я"),Cell(5, "Т"),Cell(5, "А"),]),
    ]),List.of([
      List.of([Cell(1, "К"), Cell(1, "А"), Cell(2, "М"), Cell(3, "М"),Cell(3, "Е"),Cell(3, "П"),]),
      List.of([Cell(5, "С"), Cell(1, "Р"), Cell(2, "А"), Cell(2, "Ж"),Cell(3, "Л"),Cell(3, "И"),]),
      List.of([Cell(5, "Ю"), Cell(6, "Р"), Cell(2, "С"), Cell(2, "Е"),Cell(4, "Ё"),Cell(9, "Д"),]),
      List.of([Cell(5, "А"), Cell(6, "Э"), Cell(4, "У"), Cell(4, "К"),Cell(4, "С"),Cell(9, "О"),]),
      List.of([Cell(5, "Н"), Cell(6, "Т"), Cell(7, "К"), Cell(8, "П"),Cell(8, "Е"),Cell(9, "Р"),]),
      List.of([Cell(6, "С"), Cell(6, "У"), Cell(7, "У"), Cell(7, "Ӝ"),Cell(8, "Л"),Cell(8, "Ь"),]),
  ]),List.of([
      List.of([Cell(1, "Д"), Cell(1, "Н"), Cell(1, "Е"), Cell(2, "П"),Cell(2, "А"),Cell(2, "Л"),]),
      List.of([Cell(1, "У"), Cell(1, "Н"), Cell(7, "П"), Cell(2, "О"),Cell(2, "П"),Cell(2, "Ь"),]),
      List.of([Cell(6, "С"), Cell(6, "Ы"), Cell(7, "У"), Cell(2, "Т"),Cell(2, "О"),Cell(2, "Н"),]),
      List.of([Cell(6, "А"), Cell(6, "Л"), Cell(7, "З"), Cell(5, "Ӧ"),Cell(5, "Р"),Cell(3, "Л"),]),
      List.of([Cell(6, "Л"), Cell(4, "Й"), Cell(4, "В"), Cell(3, "Р"),Cell(3, "О"),Cell(3, "Ы"),]),
      List.of([Cell(4, "Ш"), Cell(4, "А"), Cell(4, "Ы"), Cell(4, "Л"),Cell(3, "Ш"),Cell(3, "М"),]),
  ]),List.of([
      List.of([Cell(1, "К"), Cell(1, "О"), Cell(1, "Н"), Cell(2, "З"),Cell(2, "А"),Cell(2, "Р"),]),
      List.of([Cell(3, "В"), Cell(1, "Ы"), Cell(1, "Ь"), Cell(7, "К"),Cell(2, "И"),Cell(2, "Н"),]),
      List.of([Cell(3, "Ӧ"), Cell(4, "Т"), Cell(8, "Д"), Cell(7, "О"),Cell(7, "Н"),Cell(7, "Ь"),]),
      List.of([Cell(3, "Й"), Cell(4, "Р"), Cell(8, "Ы"), Cell(7, "Н"),Cell(7, "О"),Cell(7, "Д"),]),
      List.of([Cell(4, "П"), Cell(4, "У"), Cell(8, "Р"), Cell(6, "С"),Cell(6, "Ы"),Cell(6, "К"),]),
      List.of([Cell(5, "М"), Cell(5, "А"), Cell(5, "Р"), Cell(5, "У"),Cell(6, "Ш"),Cell(6, "Ы"),]),
  ]),List.of([
      List.of([Cell(1, "Ч"), Cell(2, "П"), Cell(2, "А"), Cell(2, "Р"),Cell(4, "У"),Cell(4, "Ш"),]),
      List.of([Cell(1, "И"), Cell(5, "Н"), Cell(2, "Ь"), Cell(2, "С"),Cell(4, "М"),Cell(3, "Н"),]),
      List.of([Cell(1, "П"), Cell(5, "Ю"), Cell(5, "Л"), Cell(5, "Э"),Cell(5, "С"),Cell(3, "И"),]),
      List.of([Cell(1, "Е"), Cell(5, "Т"), Cell(5, "Р"), Cell(5, "У"),Cell(5, "М"),Cell(6, "И"),]),
      List.of([Cell(1, "Й"), Cell(6, "Т"), Cell(6, "К"), Cell(6, "О"),Cell(6, "Н"),Cell(6, "Б"),]),
      List.of([Cell(6, "К"), Cell(6, "У"), Cell(6, "У"), Cell(6, "Л"),Cell(6, "Г"),Cell(6, "У"),]),
  ]),List.of([
      List.of([Cell(1, "С"), Cell(1, "Ю"), Cell(2, "Ш"), Cell(2, "У"),Cell(2, "М"),Cell(2, "П"),]),
      List.of([Cell(1, "Е"), Cell(1, "Р"), Cell(2, "Н"), Cell(2, "О"),Cell(2, "Т"),Cell(2, "О"),]),
      List.of([Cell(1, "С"), Cell(5, "К"), Cell(5, "О"), Cell(5, "Р"),Cell(5, "К"),Cell(5, "А"),]),
      List.of([Cell(3, "А"), Cell(3, "З"), Cell(4, "А"), Cell(4, "К"),Cell(5, "Ё"),Cell(5, "К"),]),
      List.of([Cell(3, "Н"), Cell(3, "И"), Cell(3, "Н"), Cell(4, "Ь"),Cell(5, "З"),Cell(5, "У"),]),
      List.of([Cell(3, "О"), Cell(3, "К"), Cell(3, "С"), Cell(4, "С"),Cell(4, "Я"),Cell(4, "С"),]),
  ]),
]);
List<List<List<Cell>>> challengeLevels = List.of([
  List.of([
    List.of([Cell(3, "У"), Cell(3, "Ж"), Cell(1, "П"),]),
    List.of([Cell(4, "У"), Cell(4, "Н"), Cell(1, "У"), ]),
    List.of([Cell(4, "Д"), Cell(2, "Ы"), Cell(2, "Ж"), ]),
  ]),List.of([
    List.of([Cell(1, "Ж"), Cell(3, "Р"), Cell(2, "Ы"),]),
    List.of([Cell(1, "Ы"), Cell(3, "А"), Cell(2, "П"), ]),
    List.of([Cell(1, "П"), Cell(2, "Т"), Cell(2, "Ы"), ]),
  ]),List.of([
    List.of([Cell(2, "Д"), Cell(1, "Ы"), Cell(1, "Ж"),]),
    List.of([Cell(2, "У"), Cell(1, "В"), Cell(3, "К"), ]),
    List.of([Cell(2, "Р"), Cell(3, "Й"), Cell(3, "Ы"), ]),
  ]),List.of([
    List.of([Cell(1, "Б"), Cell(2, "Ы"), Cell(2, "Р"),]),
    List.of([Cell(1, "А"), Cell(2, "Н"), Cell(2, "У"), ]),
    List.of([Cell(1, "К"), Cell(1, "А"), Cell(2, "Т"), ]),
  ]),
]);
class Cell {
  Cell(this.wordId, this.letter);
  String letter;
  int wordId;
  bool selected = false;
  bool isKnown = false;
}

List<List<String>> allLevelWordsUDM = List.of([
  List.of(["ПУ","ЫЖ","УЖ","ДУН",]),
  List.of(["ПЫЖ","ТЫПЫ","АР",]),
  List.of(["ВЫЖ","ДУР","КЫЙ",]),
  List.of(["БАКА","ТУРЫН",]),
  List.of(["САЕС","ЭШ","МУГ",]),
  List.of(["ИВОР","ДӦДЬЫ",]),
  List.of(["ПӦЙШУР","ТӤР",]),
  List.of(["АПАЙ","КЕНЕШ",]),
  List.of(["МАЛПАН","БУС",]),
  List.of(["КИОН", "ӞИЧЫ", "ОШ", "ГОНДЫР",]),
  List.of(["КОРКА", "УКНО",  "КУАР","ӜӦК",]),
  List.of(["КУАКА", "ШУНДЫ","БЕРИЗЬ",]),
  List.of(["СЮКАСЬ","ЧОРЫГ","КЕШЫР",]),
  List.of(["СУГОН","МАКЕС","ПУКСЁН",]),
  List.of(["АРЪЯН","БАМ","ПЫШТУРЫН",]),
  List.of(["ЭМЕЗЬ","НЫР","ЙЫР","АРАКЫ",]),
  List.of(["КЫЛБУР","МАЙТАЛ","СКАЛ",]),
  List.of(["КУТ","ИЗЬЫ","КЫШЕТ","ЛЬӦМ",]),
  List.of(["КЫЗ","ГУЖЕМ","ӴӦЖ","НЮЛЭС",]),
  List.of(["ЧИБИНЬ","СӤЛЬ","ТУСЬТЫ",]),
  List.of(["МУНЧО","КОРТ","БЫЖ","АНАЙ",]),
  List.of(["ЛЯЛЬЧИ","ВУНЫЛ","ӞАЗЕГ",]),
  List.of(["ВЫН","КАРНАН","ДӤСЬ","ГИД",]),
  List.of(["ПИСПУ","ТОЛЭЗЬ","АЗБАР","АНДАН","ВИЗЬ",]),
  List.of(["ВОЗЬ","БАТЫР","ВЕДӤН","ВӦЁГУБИ","ЁРОС",]),
  List.of(["ЕМЫШ","ВОТЭС","БАКЧА","ГУДЫРИ","УРОБО",]),
  List.of(["ДЫШЕТСКОН","ВЕНЬ","ВӦЛДЭТ","АРБЕРИ",]),
  List.of(["УЙВӦТ","ӜӦККЫШЕТ","ӦС","ЛАПАС","КОӴЫШ",]),
  List.of(["АДЯМИ","ЭКСЭЙ","ДУШЕС","ВАМЫШ","СЭРЕГ",]),
  List.of(["ВИРНУНАЛ","ГОРДКУШМАН","ТАШБАКА",]),
  List.of(["ЙӦ","КУРЕГ","СЮСЬТЫЛ","ЛЫМЫ","ВЫЖЫКЫЛ",]),
  List.of(["АТАС","ТЭЛЬ","ЗОРКИБЫ","БӦДЁНО","ДУРЫ",]),
  List.of(["УЗЫ","БУБЫЛИ","ТЫМЕТ","ЛЕМТЭЙ","АЙШЕТ",]),
  List.of(["ӞОЛЬГЫРИ","НУМЫР","ЮСЬ","ӴЫН","СӤЗЬЫЛ",]),
  List.of(["КУЖЫМ","НЯНЬ","ТЫПЫРТОН", "КУАЗЬ","ГУР",]),
  List.of(["ЭБЕК","ПУШМУЛЬЫ","СЯРТЧЫ","ПАНЬТЭМ",]),
  List.of(["ШЫД","КЫМЕС","ПЕЛЬНЯНЬ","ВАЛ","ГУБИ","ВУ",]),
  List.of(["ЧИНЬЫ","ПАЛЭЗЬ","БОРЫ","ТУЛЫС","БАДЯР",]),
  List.of(["ГУЛБЕЧ","ВАЛЭКТОН","ЙЫРСИ","ПЫӴАЛ","БУДОС","ЛЫМЫ","ГУР",]),
  List.of(["АГАЙ","НЮК","МУЗЪЕМ","ПАСЬ","ЕТӤН","ВИЗЬСЫНАН","ТУШМОН",]),
  List.of(["ИНБАМ","ДАУР","ГОЗЫ","СУРЕД","ОГИН","ПУНЫ","ГИЖЫ","МИЛЬЫМ",]),
  List.of(["ВЕРАСЬКОН","КУШМАН","ГЫРЛЫ","ИНСЬӦР","АРАМА","ЫРГОН"]),
  List.of(["ЯРАТОН","КАПКА","ВАЛЕС","ГУРТ","ЛУЛЧЕБЕРЕТ","МИНДЭР",]),
  List.of(["ВУКАРНАН","ГЕРЫ","ГАЖАН","ГОРДСЮЙ","ГУЖДОР","ӴУШЪЯЛ",]),
  List.of(["СЮЛЭМ","ПУЖЫМ","КОЙЫК","ДУРИНЧИ","ДЭРЕМ","ПУКОН","УЛМО",]),
  List.of(["ВОЖВЫЛЪЯСЬКОН","ОЖГАРЧИ","ДАРТ","СИН","ЭШЪЯСЬКОН",]),
  List.of(["ПУНЬЫ","ӴОШАТСКОН","ТӦДЬЫГУБИ","ШУЛДЫРЪЯСЬКОН",]),
  List.of(["ЛЫМЫПОГ","ЛӤЯЛГУБИ","ОГРЕЧ","ЛУД","ПЕСЯТАЙ","ГУРЕЗЬ",]),
  List.of(["КАР","МАЖЕС","ПИЛЕМ","УКСЁ","СЮАН","СУТЭР","ӜУК","ПЕЛЬ","ДОР",]),
  List.of(["ДУННЕ","ПАЛЬПОТОН","ЛЫМШОР","ШАЙВЫЛ","ӦР","СЫЛАЛ","ПУЗ"]),
  List.of(["КОНЬЫ","ЗАРНИ","ВӦЙ","ПУРТ","УРАМ","ШЫКЫС","КОНЬДОН","ДЫР"]),
  List.of(["ЧИПЕЙ","ПАРСЬ","ИН","МУШ","НЮЛЭСМУРТ","КУТКУЛОНГУБИ",]),
  List.of(["СЮРЕС","ШУМПОТОН","АЗИНСКОН","СЯСЬКА","КОРКАКУЗЁ",]),
]);
List<List<String>> allLevelWordsRUS = List.of([
    List.of(["ДРОВА","ОВЦА","РАБОТА","ЦЕНА",]),
    List.of(["ПЛОТ","ДУБ","ГОД",]),
    List.of(["ЛЕСТНИЦА","КРАЙ","ЗМЕЯ",]),
    List.of(["ЖАБА","ТРАВА",]),
    List.of(["РУКАВ","ДРУГ","ПРИЧИНА",]),
    List.of(["НОВОСТЬ","САНИ",]),
    List.of(["ЗВЕРЬ","ТОПОР",]),
    List.of(["СТАРШАЯ СЕСТРА","СОВЕЩАНИЕ",]),
    List.of(["МЫСЛЬ","ТУМАН",]),
    List.of(["ВОЛК", "ЛИСА", "БЫК", "МЕДВЕДЬ",]),
    List.of(["ДОМ", "ОКНО",  "ЛИСТ","СТОЛ",]),
    List.of(["ВОРОНА","СОЛНЦЕ","ЛИПА",]),
    List.of(["КВАС","РЫБА","МОРКОВЬ",]),
    List.of(["ЛУК","БЕДРО","ВТОРНИК",]),
    List.of(["ПАХТА","ЩЕКА","ДУШИЦА",]),
    List.of(["МАЛИНА","НОС","ГОЛОВА","ВИНО",]),
    List.of(["СТИХОТВОРЕНИЕ","МЫЛО","КОРОВА",]),
    List.of(["МУХА","ШАПКА","ПЛАТОК","ЧЕРЁМУХА",]),
    List.of(["ЕЛЬ","ЛЕТО","УТКА","ЛЕС",]),
    List.of(["КОМАР","МЯСО","ТАРЕЛКА",]),
    List.of(["БАНЯ","ЖЕЛЕЗО","ХВОСТ","МАМА",]),
    List.of(["РАБОТНИК","РУСАЛКА","ГУСЬ",]),
    List.of(["МЛАДШИЙ БРАТ","КАРАМЫСЛО","ОДЕЖДА","ЗАДНИЙ ДВОР",]),
    List.of(["ДЕРЕВО","МЕСЯЦ","ДВОР","СТАЛЬ","УМ",]),
    List.of(["ЛУГ","БОГАТЫРЬ","КОЛДУН","МАСЛЁНОК","РАЙОН",]),
    List.of(["ЯГОДА","СЕТЬ","ОГОРОД","ГРОМ","ТЕЛЕГА",]),
    List.of(["УЧЁБА","ИГЛА","ПОТОЛОК","ПРЕДМЕТ",]),
    List.of(["СОН","СКАТЕРТЬ","ДВЕРЬ","САРАЙ","КОШКА",]),
    List.of(["ЧЕЛОВЕК","ЦАРЬ","ЯСТРЕБ","ШАГ","УГОЛ",]),
    List.of(["СРЕДА","СВЁКЛА","ЧЕРЕПАХА",]),
    List.of(["ЛЁД","КУРИЦА","СВЕЧА","СНЕГ","СКАЗКА",]),
    List.of(["ПЕТУХ","РОЩА","БОЖЬЯ КОРОВКА","ПЕРЕПЕЛКА","ПОВАРЁШКА",]),
    List.of(["ЗЕМЛЯНИКА","БАБОЧКА","ПРУД","КЛЕЩ","ФАРТУК",]),
    List.of(["ВОРОБЕЙ","ЧЕРВЯК","ЛЕБЕДЬ","ДЫМ","ОСЕНЬ",]),
    List.of(["СИЛА","ХЛЕБ","ПРИТОПТЫВАНИЕ", "ПОГОДА","МУЗЫКА",]),
    List.of(["ЛЯГУШКА","ОРЕХ","РЕПА","ТЁЗКА",]),
    List.of(["СУП","ЛОБ","ПЕЛЬМЕНИ","ЛОШАДЬ","ГРИБ","ВОДА",]),
    List.of(["ПАЛЕЦ","РЯБИНА","КЛУБНИКА","ВЕСНА","КЛЁН",]),
    List.of(["ПОДПОЛЬЕ","ОБЪЯСНЕНИЕ","ВОЛОСЫ","РУЖЬЁ","РАСТЕНИЕ","СНЕГ","ПЕЧЬ",]),
    List.of(["СТАРШИЙ БРАТ","ОВРАГ","ЗЕМЛЯ","ДЫРКА","ЛЁН","ЭКЗАМЕН","ВРАГ",]),
    List.of(["НЕБОСВОД","ВЕК","ВЕРЁВКА","РИСУНОК","ОБЪЕДИНЕНИЕ","СОБАКА","НОГОТЬ","БЛИН",]),
    List.of(["РАЗГОВОР","КОРНЕПЛОД","КОЛОКОЛ","КОСМОС","КУСТАРНИК","МЕДЬ"]),
    List.of(["ЛЮБОВЬ","ВОРОТА","КРОВАТЬ","ДЕРЕВНЯ","КУЛЬТУРА","ПОДУШКА",]),
    List.of(["СТРЕКОЗА","ПЛУГ","УВАЖЕНИЕ","ГЛИНА","ЛУЖАЙКА","ЁЖ",]),
    List.of(["СЕРДЦЕ","СОСНА","ЛОСЬ","ОСА","РУБАШКА, ПЛАТЬЕ","СТУЛ","ЯБЛОКО",]),
    List.of(["КОНКУРС","ВОИН","СТРАСТЬ, АЗАРТ","ГЛАЗ","ДРУЖБА",]),
    List.of(["ЛОЖКА","СОРЕВНОВАНИЕ","БЕЛЫЙ ГРИБ","ВЕСЕЛЬЕ",]),
    List.of(["СНЕГОВИК","ОПЁНОК","ОГУРЕЦ","ПОЛЕ","ДЕДУШКА","ГОРА",]),
    List.of(["ГНЕЗДО, ГОРОД","ГРАБЛИ","ОБЛАКО","ДЕНЬГИ","СВАДЬБА","СМОРОДИНА","КАША","УХО","ДОМ, РОДИНА",]),
    List.of(["МИР","УЛЫБКА","ЮГ","КЛАДБИЩЕ","РУСЛО","СОЛЬ","ЯЙЦО"]),
    List.of(["БЕЛКА","ЗОЛОТО","МАСЛО","НОЖ","УЛИЦА","СУНДУК","ДЕНЬГИ","ВРЕМЯ"]),
    List.of(["ЩУКА","СВИНЬЯ","НЕБО","ПЧЕЛА","ЛЕШИЙ","МУХОМОР",]),
    List.of(["ДОРОГА","РАДОСТЬ","УСПЕХ, РАЗВИТИЕ","ЦВЕТОК","ДОМОВОЙ",]),
]);

List<String> pictures = List.of([]);
Color backColor = Color(0xffe95257);
Color lightbackColor = Color(0xffee857f);
Color textColor = Color(0xfff19e9a);
Color text2Color = Color(0xfff5bea9);
Color lighttextColor = Color(0xfff5dbda);
int numOfLevels = allLevels[0].length + allLevels[1].length + allLevels[2].length + allLevels[3].length;
List<String> banks = List.of([
  "assets/bank.png",
  "assets/bank1-25.png",
  "assets/bank2-25.png",
  "assets/bank3-25.png",
  "assets/bank4-25.png",
  "assets/bank5-25.png",
  "assets/bank6-25.png",
  "assets/bank7-25.png",
  "assets/bank8-25.png",
  "assets/bank9-25.png",
  "assets/bank10-25.png",
  "assets/bank11-25.png",
  "assets/bank12-25.png",
  "assets/bank13-25.png",
  "assets/bank14-25.png",
  "assets/bank15-25.png",
  "assets/bank16-25.png",
  "assets/bank17-25.png",
  "assets/bank18-25.png",
  "assets/bank19-25.png",
  "assets/bank20-25.png",
  "assets/bank21-25.png",
  "assets/bank22-25.png",
  "assets/bank23-25.png",
  "assets/bank24-25.png",
  "assets/bank25-25.png",
  "assets/bank26-25.png",
  "assets/bank27-25.png",
  "assets/bank28-25.png",
  "assets/bank29-25.png",
  "assets/bank30-25.png",
  "assets/bank31-25.png",
  "assets/bank32-25.png",
  "assets/bank33-25.png",
  "assets/bank34-25.png",
  "assets/bank35-25.png",
  "assets/bank36-25.png",
  "assets/bank37-25.png",
  "assets/bank38-25.png",
  "assets/bank39-25.png",
  "assets/bank40-25.png",
  "assets/bank41-25.png",
]);
List<String> startbanks = List.of([
  "assets/startbank.png",
  "assets/startbank1-25.png",
  "assets/startbank2-25.png",
  "assets/startbank3-25.png",
  "assets/startbank4-25.png",
  "assets/startbank5-25.png",
  "assets/startbank6-25.png",
  "assets/startbank7-25.png",
  "assets/startbank8-25.png",
  "assets/startbank9-25.png",
  "assets/startbank10-25.png",
  "assets/startbank11-25.png",
  "assets/startbank12-25.png",
  "assets/startbank13-25.png",
  "assets/startbank14-25.png",
  "assets/startbank15-25.png",
  "assets/startbank16-25.png",
  "assets/startbank17-25.png",
  "assets/startbank18-25.png",
  "assets/startbank19-25.png",
  "assets/startbank20-25.png",
  "assets/startbank21-25.png",
  "assets/startbank22-25.png",
  "assets/startbank23-25.png",
  "assets/startbank24-25.png",
  "assets/startbank25-25.png",
  "assets/startbank26-25.png",
  "assets/startbank27-25.png",
  "assets/startbank28-25.png",
  "assets/startbank29-25.png",
  "assets/startbank30-25.png",
  "assets/startbank31-25.png",
  "assets/startbank32-25.png",
  "assets/startbank33-25.png",
  "assets/startbank34-25.png",
  "assets/startbank35-25.png",
  "assets/startbank36-25.png",
  "assets/startbank37-25.png",
  "assets/startbank38-25.png",
  "assets/startbank39-25.png",
  "assets/startbank40-25.png",
  "assets/startbank41-25.png",
]);
